//! Actions resolved once at the input dispatch boundary. Unknown configured actions are inert.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Action {
    Focusdown,
    Focusleft,
    Focusmon,
    Focusright,
    Focusstack,
    Focusup,
    Incnmaster,
    Killclient,
    Layoutnext,
    Layoutprev,
    Minimize,
    Quit,
    Reloadconfig,
    Restore,
    Setgaps,
    Setlayout,
    Setmfact,
    Shellcmd,
    Spawn,
    Swapdown,
    Swapleft,
    Swapright,
    Swapup,
    Swapview,
    Tag,
    Tagmon,
    Togglefloating,
    Togglefullscr,
    Togglemaximize,
    Toggletag,
    Toggletiledir,
    Toggleview,
    View,
    Viewnext,
    Viewprev,
    Zoom,
    Unknown,
}
impl From<&str> for Action {
    fn from(name: &str) -> Self {
        match name {
            "focusdown" => Self::Focusdown,
            "focusleft" => Self::Focusleft,
            "focusmon" => Self::Focusmon,
            "focusright" => Self::Focusright,
            "focusstack" => Self::Focusstack,
            "focusup" => Self::Focusup,
            "incnmaster" => Self::Incnmaster,
            "killclient" => Self::Killclient,
            "layoutnext" => Self::Layoutnext,
            "layoutprev" => Self::Layoutprev,
            "minimize" => Self::Minimize,
            "quit" => Self::Quit,
            "reloadconfig" => Self::Reloadconfig,
            "restore" => Self::Restore,
            "setgaps" => Self::Setgaps,
            "setlayout" => Self::Setlayout,
            "setmfact" => Self::Setmfact,
            "shellcmd" => Self::Shellcmd,
            "spawn" => Self::Spawn,
            "swapdown" => Self::Swapdown,
            "swapleft" => Self::Swapleft,
            "swapright" => Self::Swapright,
            "swapup" => Self::Swapup,
            "swapview" => Self::Swapview,
            "tag" => Self::Tag,
            "tagmon" => Self::Tagmon,
            "togglefloating" => Self::Togglefloating,
            "togglefullscr" => Self::Togglefullscr,
            "togglemaximize" => Self::Togglemaximize,
            "toggletag" => Self::Toggletag,
            "toggletiledir" => Self::Toggletiledir,
            "toggleview" => Self::Toggleview,
            "view" => Self::View,
            "viewnext" => Self::Viewnext,
            "viewprev" => Self::Viewprev,
            "zoom" => Self::Zoom,
            _ => Self::Unknown,
        }
    }
}
